### ISSUE TITLE
systemd

### ISSUE THREAD

**Issue by noordawod** [WhitewaterFoundry/WSLFedoraRemix#13]
Hi, and thanks for this wonderful remix!

I'm not sure whether this is a bug or a feature (intended) so that's why I chose to open a regular issue. When trying to use systemd to enable a service on boot (say, `systemctl start sshd`), I get the following error message:

**System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down**

I understand the message and I suppose this is partly because of spinning Fedora inside WSL, so just wondering is there any other recommended way to start daemons on boot?

Thanks.

**Comment by sirredbeard** [comment]
There is no init on WSL, including systemd.

The Linux image is 'booted' directly the default shell, no kernel or services are loaded.

The best way to start a service on WSL is to start with an old-fashioned init script from .bashrc or make a .bat file that calls fedoraremix.exe with the run option..

**Comment by noordawod** [comment]
Alright, thanks for the explanation. My first foray into WSL :)

**Comment by sirredbeard** [comment]
I have a primer on WSL here that you might find helpful: https://github.com/sirredbeard/Awesome-WSL
