### ISSUE TITLE
X64_install.tar.gz - is missing fedoraremix.exe 

### ISSUE THREAD

**Issue by bcurran3** [WhitewaterFoundry/WSLFedoraRemix#16]
**Describe the bug**
There is no way to execute Fedora Remix from the X64_install.tar.gz file. X64_install.tar.gz - is missing fedoraremix.exe program.

EDIT: Seems this archive is the same as install.tar.gz.  Maybe this file is only used for updates?

**To Reproduce**
Extract X64_install.tar.gz to X64_install.tar. Extract X64_install.tar to get the distro files. No .EXE found.

**Expected behavior**
A method to execute Fedora Remix; i.e. fedoraremix.exe as found in DistroLauncher-Appx_1.0.26.0_x64.appx

**Screenshots**
![image](https://user-images.githubusercontent.com/14026600/51495979-14dd4200-1d73-11e9-9d6e-3d15aa5a1501.png)

![image](https://user-images.githubusercontent.com/14026600/51495990-1d357d00-1d73-11e9-9c46-2d625820a06e.png)

**WLinux Version**

1.0.26.0

**Comment by sirredbeard** [comment]
The X64_install.tar.gz and ARM64_install.tar.gz are the rootfs images unpacked by the UWP wrapper on installation on respective platforms.

They should be renamed to simply install.tar.gz and placed in the X64 or ARM64 directory and then the project can be built from the Visual Studio solution.

We make the rootfs images available for people who want to build from source without building the images themselves.

We also post them so users can independently verify or tweak our rootfs images.

We also make our rootfs image building script available too for users who do want to build the whole thing from source, including the rootfs image.
