### ISSUE TITLE
'dnf update' installs previously uninstalled packages

### ISSUE THREAD

**Issue by grufwub** [WhitewaterFoundry/WSLFedoraRemix#2]
**Describe the bug**
In the tar.gz build process we remove linux-firmware and dracut, but upon performing 'dnf update' on a WLS build if certain packages are updated then they automatically get pulled back in as a dependency. During the install process, the scriptlets also fail down to a number of issues:

"dracut: No '/dev/log' or 'logger' included for syslog logging
libkmod: kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
dracut-install: Could not get list of loaded modules: Unknown error -2. Switching to non-hostonly mode.
libkmod: kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory"

Removing the packages again can be performed with no issues and no dependency breakage.

Linux-firmware contains firmware for Linux kernel drivers and dracut is an initramfs structure, so likely not being used on WSL regardless of being pulled back in as a dependency. We could either look into leaving these installed (but find a way of silencing expected errors?), or ensure that they are locked from being reinstalled at least automatically.

**WLinux Version**
Fedora Remix for WSL 1.0.16.0

**Windows Build**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Alienware 1.4.2, 17/08/2018

**Comment by sirredbeard** [comment]
Maybe add them to excludepkgs in dnf.conf?

**Comment by grufwub** [comment]
I've tried adding the packages to excludes in dnf.conf, unfortunately doesn't work. Other options could include (if possible): custom post-install scripts, eventually including our own repository with certain packages like kernel-core using reduced dependency sets, maybe making our own 'package group' recognised by DNF if that could help?

Otherwise, trying to silence the errors.
