### ISSUE TITLE
Add details of modifications to README

### ISSUE THREAD

**Issue by thomasfedb** [WhitewaterFoundry/WSLFedoraRemix#3]
Would be excellent for `README.md` to include brief details of how and where WSLFedora differs from a stock Fedora image.

**Comment by sirredbeard** [comment]
Agreed.

Note we specifically have to say "Fedora Remix for WSL contains modifications to the official Fedora distribution." under the terms of the Fedora Remix program.

Other than some excluding irrelevant packages like linux-firmware and very minor configuration settings we do not actually modify much though.

We may later bundle wslutilities once it is ported to rpm.

**Comment by sirredbeard** [comment]
See https://github.com/WhitewaterFoundry/WSLFedoraRemix#differences-from-upstream-fedora.
