### ISSUE TITLE
dnf upgrade fails: Cannot rename directory, permission denied

### ISSUE THREAD

**Issue by mmmmmmbeer** [WhitewaterFoundry/WSLFedoraRemix#4]
**Description**
Post-install (have only set up user account), attempting to run `sudo dnf upgrade`
dnf errors out after fetching repodata:

`Error: Cannot rename directory "/var/cache/dnf/fedora-8c9e363c32277c01/tmpdir.bTBG4X/repodata" to "/var/cache/dnf/fedora-8c9e363c32277c01/repodata": Permission denied`

**To Reproduce**
1. Attempt dnf upgrade (sudo)
2. See error

**Expected behavior**
Since dnf was executed with sudo, I would expect these privileges to carry through the transaction (not to error out due to permissions).

**Screenshot**
![image](https://user-images.githubusercontent.com/16092016/49818841-c97e4f80-fd41-11e8-91cd-c08d382ce6f4.png)

**What other troubleshooting have you attempted?**

Ran `sudo dnf clean all`; Error persists

**App/System Info**

App Version 1.0.17.0

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO R06ET58W (1.32 ), 12/15/2017

**Comment by mmmmmmbeer** [comment]
So...I just kept running `sudo dnf upgrade` out of frustration, and noticed the fedora repo finished successfully. I ran it three more times, and eventually got past the "permission denied" error for the updates repo as well.

I honestly have no idea what happened here. I browsed the /var/cache/dnf directory structure a bit and ensured all folders/files were root:root (they were), but made no changes whatsoever. I'm stumped.

**Comment by sirredbeard** [comment]
Odd. We will keep an eye out for this and try to reproduce. 

It could be an issue from the yum cache that comes over from the image build.

I know some some yum cache needs to stay.

We might need to tweak some permissions on it though.

We need to check if the user bit is set on /var/cache/dnf.

**Comment by grufwub** [comment]
I tried running 'dnf upgrade' on my personally compiled install with no issues. Then installed from Microsoft Store, did the same and also ran into no issues. Strange 🤔.

Had you made any modifications to your Fedora WSL build before performing this? Installed anything, edited any config files? Just trying to figure out if this is an odd bug that crops up over time, or if certain packages might cause this to happen specifically on WSL.

**Comment by mmmmmmbeer** [comment]
I installed from the Microsoft Store, no modifications made. Only created user account and password, then ran `sudo dnf upgrade`

**Comment by grufwub** [comment]
Very odd. I'll do some more testing see if I can reproduce and work on it!

**Comment by Conan-Kudo** [comment]
@sirredbeard It's safe to purge everything in `/var/cache/dnf` and `/var/cache/yum` near the end of the image build process. That should resolve these issues. Just don't delete `/var/cache/dnf` or `/var/cache/yum` directories themselves.
