### ISSUE TITLE
Create and maintain package for NTPSec

### ISSUE THREAD

**Issue by DarthSpock** [WhitewaterFoundry/WSLFedoraRemix#9]
**Is your feature request related to a problem? Please describe.**

Technically no. 

**Describe the solution you'd like**

Looking to migrate from NTP Classic to NTPSec in a way that allows quick deployment across the network in a manner that allows easy patching via repo server.

**Describe alternatives you've considered**

1) Build from source and deploy via Fabric. Would need to ensure dependencies are installed first.

2) Create our own dnf/yum package using https://github.com/ntpsec/ntpsec/blob/master/INSTALL and maintain it as incremental updates are pushed. (More likely to happen in short-term).

**Additional context**

Since repo servers are being stood up for Wlinux and possibly WSLFedoraRemix/WLE, I was hoping to have an easy automated means of updating the network whenever an update for NTPSec occurs. Debian Testing and SID already have the package in existence from research conducted so Wlinux itself wouldn't need to create it, just WSLFedoraRemix. OpenSuse also has an rpm package but after raising the issue on Fedora Forums about whether a package was available and providing same information as here, was told that the OpenSuse rpm package would not likely be compatible and isn't available for Fedora/CentOS/RHEL. I have requested an official package to be available but in case that doesn't get approved and released, I would hope it could be provided the new repo servers being built  (or place in the EPEL repo).

**Comment by sirredbeard** [comment]
I think that would something you could do using COPR and should go into upstream Fedora.

**Comment by Conan-Kudo** [comment]
@DarthSpock I personally would recommend the usage of `chrony` instead. But if you really want NTPSec, you should consider [contributing to Fedora and maintaining a package there](https://fedoraproject.org/wiki/Join_the_package_collection_maintainers#How_to_join_the_Fedora_Package_Collection_Maintainers.3F).
